# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProgrammaticallyExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProgrammaticallyExample
	pod 'Alamofire', '~> 4.8.2'
  target 'ProgrammaticallyExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProgrammaticallyExampleUITests' do
    # Pods for testing
  end

end
